sonar.projectKey=cervantesh_convex-go
sonar.projectName=convex-go
sonar.sources=.
sonar.exclusions=**/vendor/**,tmp/**,dist/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/*_test.go
sonar.go.activate=true
sonar.go.file.suffixes=.go
sonar.go.exclusions=**/vendor/**
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=test-report.out
sonar.go.golangci-lint.reportPaths=golangci-report.json
