package codegen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateScansConvexSourcesAndEmitsDeterministicRefs(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "messages.ts"), `
import { query, mutation } from "./_generated/server";

export const list = query({
  handler: async () => [],
});

export const send = mutation({
  handler: async () => null,
});
`)
	writeFile(t, filepath.Join(dir, "jobs", "daily.ts"), `
import { action } from "../_generated/server";

export const run = action({
  handler: async () => null,
});
`)
	writeFile(t, filepath.Join(dir, "internal", "admin.ts"), `
import { internalMutation, internalQuery } from "../_generated/server";

export const audit = internalQuery({
  handler: async () => null,
});

export const rebuild = internalMutation({
  handler: async () => null,
});
`)
	writeFile(t, filepath.Join(dir, "_generated", "api.d.ts"), `
export const shouldNotAppear = query({});
`)

	got, err := Generate(Config{
		SourceDir:   dir,
		PackageName: "convexapi",
		ImportPath:  "github.com/cervantesh/convex-go",
	})
	if err != nil {
		t.Fatal(err)
	}
	body := string(got)

	for _, want := range []string{
		"// Code generated by convex-go-codegen; DO NOT EDIT.",
		"package convexapi",
		`import convex "github.com/cervantesh/convex-go"`,
		`var InternalAdminAudit = convex.NewQueryReference[map[string]any, any]("internal/admin:audit")`,
		`var InternalAdminRebuild = convex.NewMutationReference[map[string]any, any]("internal/admin:rebuild")`,
		`var JobsDailyRun = convex.NewActionReference[map[string]any, any]("jobs/daily:run")`,
		`var MessagesList = convex.NewQueryReference[map[string]any, []any]("messages:list")`,
		`var MessagesSend = convex.NewMutationReference[map[string]any, any]("messages:send")`,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("generated output missing %q:\n%s", want, body)
		}
	}
	if strings.Contains(body, "ShouldNotAppear") {
		t.Fatalf("generated output must ignore _generated files:\n%s", body)
	}
	if strings.Index(body, "InternalAdminAudit") > strings.Index(body, "MessagesList") {
		t.Fatalf("generated refs must be sorted deterministically:\n%s", body)
	}
}

func TestGenerateSanitizesIdentifiersAndRejectsDuplicateNames(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "admin-tools", "2jobs.ts"), `
import { query } from "../_generated/server";

export const delete = query({
  handler: async () => null,
});
`)
	got, err := Generate(Config{SourceDir: dir, PackageName: "api", ImportPath: "github.com/cervantesh/convex-go"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), `var AdminToolsN2jobsDelete = convex.NewQueryReference[map[string]any, any]("admin-tools/2jobs:delete")`) {
		t.Fatalf("identifier was not sanitized as expected:\n%s", got)
	}

	duplicateDir := t.TempDir()
	writeFile(t, filepath.Join(duplicateDir, "foo-bar.ts"), `export const baz = query({});`)
	writeFile(t, filepath.Join(duplicateDir, "foo_bar.ts"), `export const baz = query({});`)
	if _, err := Generate(Config{SourceDir: duplicateDir, PackageName: "api", ImportPath: "github.com/cervantesh/convex-go"}); err == nil {
		t.Fatal("expected duplicate generated identifier error")
	}
}

func TestGenerateDetectsSourceExtensionsTypedExportsAndDefaultExports(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "queries.tsx"), `export const typed: PublicQuery = query({});`)
	writeFile(t, filepath.Join(dir, "mutations.jsx"), `export const save = mutation({});`)
	writeFile(t, filepath.Join(dir, "actions.js"), `export default action({});`)

	got, err := Generate(Config{SourceDir: dir, PackageName: "api", ImportPath: "github.com/cervantesh/convex-go"})
	if err != nil {
		t.Fatal(err)
	}
	body := string(got)
	for _, want := range []string{
		`var ActionsDefault = convex.NewActionReference[map[string]any, any]("actions:default")`,
		`var MutationsSave = convex.NewMutationReference[map[string]any, any]("mutations:save")`,
		`var QueriesTyped = convex.NewQueryReference[map[string]any, any]("queries:typed")`,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("generated output missing %q:\n%s", want, body)
		}
	}
}

func TestGenerateIgnoresCommentsStringsAndNonFunctionFiles(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "messages.ts"), `
// export const commented = query({});
const literal = "export const stringy = mutation({})";
const template = `+"`export const templated = action({})`"+`;
/*
export const blockCommented = internalQuery({});
*/
export const list = query({});
`)
	writeFile(t, filepath.Join(dir, "schema.ts"), `export default defineSchema({});`)
	writeFile(t, filepath.Join(dir, "node_modules", "ignored.ts"), `export const dependency = query({});`)
	writeFile(t, filepath.Join(dir, ".git", "ignored.ts"), `export const git = query({});`)

	got, err := Generate(Config{SourceDir: dir, PackageName: "api", ImportPath: "github.com/cervantesh/convex-go"})
	if err != nil {
		t.Fatal(err)
	}
	body := string(got)
	if !strings.Contains(body, "MessagesList") {
		t.Fatalf("expected real export in generated output:\n%s", body)
	}
	for _, blocked := range []string{"Commented", "Stringy", "Templated", "BlockCommented", "Dependency", "Git", "SchemaDefault"} {
		if strings.Contains(body, blocked) {
			t.Fatalf("generated output included ignored symbol %q:\n%s", blocked, body)
		}
	}
}

func TestGenerateValidatesConfig(t *testing.T) {
	if _, err := Generate(Config{}); err == nil {
		t.Fatal("expected missing source dir error")
	}
	dir := t.TempDir()
	notDir := filepath.Join(dir, "not-dir.ts")
	writeFile(t, notDir, `export const list = query({});`)
	if _, err := Generate(Config{SourceDir: notDir, PackageName: "api", ImportPath: "github.com/cervantesh/convex-go"}); err == nil {
		t.Fatal("expected source path file error")
	}
	if _, err := Generate(Config{SourceDir: dir, PackageName: "bad-package", ImportPath: "github.com/cervantesh/convex-go"}); err == nil {
		t.Fatal("expected invalid package name error")
	}
	if _, err := Generate(Config{SourceDir: dir, PackageName: "api"}); err == nil {
		t.Fatal("expected missing import path error")
	}
}

func TestCodegenHelperEdgeCases(t *testing.T) {
	if isSourceFile("schema.txt") {
		t.Fatal("txt file should not be a source file")
	}
	if refKind("unknown") != "" {
		t.Fatal("unknown ref kind should be empty")
	}
	if constructor("unknown") != "" {
		t.Fatal("unknown constructor should be empty")
	}
	if got := exportedVarName("$", "$"); got != "Function" {
		t.Fatalf("unexpected fallback var name: %q", got)
	}
	if got := titleIdentifierPart(""); got != "" {
		t.Fatalf("empty title part should stay empty, got %q", got)
	}
	for _, invalid := range []string{"", "1api", "bad-name"} {
		if isGoIdentifier(invalid) {
			t.Fatalf("%q should not be a valid Go identifier", invalid)
		}
	}
	stripped := stripCommentsAndStrings("const s = \"escaped \\\" export const nope = query({})\";\nexport const yes = query({});")
	if strings.Contains(stripped, "nope") || !strings.Contains(stripped, "export const yes = query") {
		t.Fatalf("unexpected stripped source: %q", stripped)
	}
}

func TestCodegenHardeningExactValidationErrors(t *testing.T) {
	if _, err := Generate(Config{}); err == nil || err.Error() != "convex-go-codegen: source dir is required" {
		t.Fatalf("unexpected missing source dir error: %v", err)
	}
	dir := t.TempDir()
	if _, err := Generate(Config{SourceDir: dir, PackageName: "bad-package", ImportPath: "github.com/cervantesh/convex-go"}); err == nil || err.Error() != `convex-go-codegen: invalid package name "bad-package"` {
		t.Fatalf("unexpected invalid package error: %v", err)
	}
	if _, err := Generate(Config{SourceDir: dir, PackageName: "api"}); err == nil || err.Error() != "convex-go-codegen: import path is required" {
		t.Fatalf("unexpected missing import error: %v", err)
	}
	notDir := filepath.Join(dir, "not-dir.ts")
	writeFile(t, notDir, `export const list = query({});`)
	if _, err := Generate(Config{SourceDir: notDir, PackageName: "api", ImportPath: "github.com/cervantesh/convex-go"}); err == nil || !strings.Contains(err.Error(), "is not a directory") {
		t.Fatalf("unexpected not-dir error: %v", err)
	}
}

func TestCodegenHardeningScansAndSortsRefsExactly(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "zeta.ts"), `
export const zebra = mutation({});
export const alpha = query({});
`)
	writeFile(t, filepath.Join(dir, "alpha.ts"), `export default query({});`)
	writeFile(t, filepath.Join(dir, "alpha", "beta.tsx"), `export const run = action({});`)

	refs, err := scanSourceDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := []functionRef{
		{ModulePath: "alpha", Name: "default", Kind: "query", VarName: "AlphaDefault", ResultType: ""},
		{ModulePath: "alpha/beta", Name: "run", Kind: "action", VarName: "AlphaBetaRun", ResultType: ""},
		{ModulePath: "zeta", Name: "alpha", Kind: "query", VarName: "ZetaAlpha", ResultType: ""},
		{ModulePath: "zeta", Name: "zebra", Kind: "mutation", VarName: "ZetaZebra", ResultType: ""},
	}
	if len(refs) != len(want) {
		t.Fatalf("expected %d refs, got %#v", len(want), refs)
	}
	for i := range want {
		if refs[i] != want[i] {
			t.Fatalf("ref %d = %#v, want %#v", i, refs[i], want[i])
		}
	}
}

func TestCodegenHardeningStripCommentsAndStringsEdges(t *testing.T) {
	source := strings.Join([]string{
		`// export const lineComment = query({});`,
		`const escaped = "not real \" export const stringy = mutation({})";`,
		"const templated = `not real\nexport const templateAction = action({})`;",
		`/* export const blockComment = internalQuery({}); */`,
		`export const real = internalAction({});`,
		`const unterminated = "export const nope = query({})`,
	}, "\n")
	stripped := stripCommentsAndStrings(source)
	for _, blocked := range []string{"lineComment", "stringy", "templateAction", "blockComment", "nope"} {
		if strings.Contains(stripped, blocked) {
			t.Fatalf("stripped source leaked %q:\n%s", blocked, stripped)
		}
	}
	if !strings.Contains(stripped, "export const real = internalAction") {
		t.Fatalf("stripped source lost real export:\n%s", stripped)
	}
	if strings.Count(stripped, "\n") != strings.Count(source, "\n") {
		t.Fatalf("stripCommentsAndStrings should preserve newline count: %q", stripped)
	}
	if len(stripped) != len(source) {
		t.Fatalf("stripCommentsAndStrings should preserve byte length: got %d, want %d", len(stripped), len(source))
	}

	trailingLineComment := `export const real = query({}); // export const fake = mutation({});`
	stripped = stripCommentsAndStrings(trailingLineComment)
	if !strings.Contains(stripped, "export const real = query") {
		t.Fatalf("stripped source lost export before trailing comment:\n%s", stripped)
	}
	if strings.Contains(stripped, "fake") {
		t.Fatalf("stripped source leaked trailing EOF line comment:\n%s", stripped)
	}
	if len(stripped) != len(trailingLineComment) {
		t.Fatalf("trailing line comment strip should preserve byte length: got %d, want %d", len(stripped), len(trailingLineComment))
	}

	unterminatedThenReal := "const bad = \"unterminated\nexport const recovered = query({});"
	stripped = stripCommentsAndStrings(unterminatedThenReal)
	if !strings.Contains(stripped, "export const recovered = query") {
		t.Fatalf("stripped source should recover after unterminated string newline:\n%s", stripped)
	}
	if len(stripped) != len(unterminatedThenReal) {
		t.Fatalf("unterminated string strip should preserve byte length: got %d, want %d", len(stripped), len(unterminatedThenReal))
	}

	unterminatedBlock := "/* export const hidden = query({})"
	stripped = stripCommentsAndStrings(unterminatedBlock)
	if strings.Contains(stripped, "hidden") || strings.Contains(stripped, "*/") {
		t.Fatalf("stripped source leaked unterminated block comment content:\n%s", stripped)
	}
	if len(stripped) != len(unterminatedBlock) {
		t.Fatalf("unterminated block strip should preserve byte length: got %d, want %d", len(stripped), len(unterminatedBlock))
	}

	closedBlock := "/* export const hidden = query({}) */"
	stripped = stripCommentsAndStrings(closedBlock)
	if strings.Contains(stripped, "hidden") || strings.Contains(stripped, "*/") {
		t.Fatalf("stripped source leaked closed block comment content:\n%s", stripped)
	}
	if len(stripped) != len(closedBlock) {
		t.Fatalf("closed block strip should preserve byte length: got %d, want %d", len(stripped), len(closedBlock))
	}
}

func TestCodegenHardeningHelperMappings(t *testing.T) {
	for input, want := range map[string]string{
		"query":            "query",
		"internalQuery":    "query",
		"mutation":         "mutation",
		"internalMutation": "mutation",
		"action":           "action",
		"internalAction":   "action",
		"unknown":          "",
	} {
		if got := refKind(input); got != want {
			t.Fatalf("refKind(%q) = %q, want %q", input, got, want)
		}
	}
	for input, want := range map[string]string{
		"query":    "NewQueryReference",
		"mutation": "NewMutationReference",
		"action":   "NewActionReference",
		"unknown":  "",
	} {
		if got := constructor(input); got != want {
			t.Fatalf("constructor(%q) = %q, want %q", input, got, want)
		}
	}
	for input, want := range map[string]string{
		"messages/list":     "MessagesList",
		"admin-tools/2jobs": "AdminToolsN2jobs",
		"$":                 "Function",
		"123":               "N123",
	} {
		if got := exportedVarName(input, ""); got != want {
			t.Fatalf("exportedVarName(%q, \"\") = %q, want %q", input, got, want)
		}
	}
	if titleIdentifierPart("\xff") != "" {
		t.Fatal("invalid utf8 title part should be empty")
	}
}

func writeFile(t *testing.T, path string, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}
