package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"
)

// Config controls Go API reference generation.
type Config struct {
	SourceDir   string
	PackageName string
	ImportPath  string
}

type functionRef struct {
	ModulePath string
	Name       string
	Kind       string
	VarName    string
	ResultType string
}

var exportedFunctionPattern = regexp.MustCompile(`(?m)export\s+const\s+([A-Za-z_$][A-Za-z0-9_$]*)(?:\s*:\s*[^=]+)?\s*=\s*(query|mutation|action|internalQuery|internalMutation|internalAction)\s*\(`)
var defaultFunctionPattern = regexp.MustCompile(`(?m)export\s+default\s+(query|mutation|action|internalQuery|internalMutation|internalAction)\s*\(`)

// Generate scans a Convex functions directory and returns a formatted Go file
// containing typed function references.
func Generate(config Config) ([]byte, error) {
	if strings.TrimSpace(config.SourceDir) == "" {
		return nil, fmt.Errorf("convex-go-codegen: source dir is required")
	}
	if !isGoIdentifier(config.PackageName) {
		return nil, fmt.Errorf("convex-go-codegen: invalid package name %q", config.PackageName)
	}
	if strings.TrimSpace(config.ImportPath) == "" {
		return nil, fmt.Errorf("convex-go-codegen: import path is required")
	}
	info, err := os.Stat(config.SourceDir)
	if err != nil {
		return nil, fmt.Errorf("convex-go-codegen: source dir: %w", err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("convex-go-codegen: source path %q is not a directory", config.SourceDir)
	}
	refs, err := scanSourceDir(config.SourceDir)
	if err != nil {
		return nil, err
	}
	return render(config.PackageName, config.ImportPath, refs)
}

func scanSourceDir(sourceDir string) ([]functionRef, error) {
	var refs []functionRef
	err := filepath.WalkDir(sourceDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			switch entry.Name() {
			case "_generated", "node_modules", ".git":
				return filepath.SkipDir
			}
			return nil
		}
		if !isSourceFile(path) {
			return nil
		}
		modulePath, err := modulePath(sourceDir, path)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		source := stripCommentsAndStrings(string(data))
		for _, match := range exportedFunctionPattern.FindAllStringSubmatchIndex(source, -1) {
			refs = append(refs, functionRef{
				ModulePath: modulePath,
				Name:       source[match[2]:match[3]],
				Kind:       refKind(source[match[4]:match[5]]),
				ResultType: inferResultType(string(data), source, match[1]-1),
			})
		}
		for _, match := range defaultFunctionPattern.FindAllStringSubmatchIndex(source, -1) {
			refs = append(refs, functionRef{
				ModulePath: modulePath,
				Name:       "default",
				Kind:       refKind(source[match[2]:match[3]]),
				ResultType: inferResultType(string(data), source, match[1]-1),
			})
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("convex-go-codegen: scan source dir: %w", err)
	}
	sort.Slice(refs, func(i, j int) bool {
		if refs[i].ModulePath != refs[j].ModulePath {
			return refs[i].ModulePath < refs[j].ModulePath
		}
		return refs[i].Name < refs[j].Name
	})
	seen := map[string]functionRef{}
	for i := range refs {
		refs[i].VarName = exportedVarName(refs[i].ModulePath, refs[i].Name)
		if previous, ok := seen[refs[i].VarName]; ok {
			return nil, fmt.Errorf("convex-go-codegen: generated identifier %s is ambiguous for %s:%s and %s:%s", refs[i].VarName, previous.ModulePath, previous.Name, refs[i].ModulePath, refs[i].Name)
		}
		seen[refs[i].VarName] = refs[i]
	}
	return refs, nil
}

func render(packageName string, importPath string, refs []functionRef) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by convex-go-codegen; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "package %s\n\n", packageName)
	fmt.Fprintf(&out, "import convex %q\n\n", importPath)
	for _, ref := range refs {
		resultType := ref.ResultType
		if resultType == "" {
			resultType = "any"
		}
		fmt.Fprintf(&out, "// %s references Convex function %s:%s.\n", ref.VarName, ref.ModulePath, ref.Name)
		fmt.Fprintf(&out, "var %s = convex.%s[map[string]any, %s](%q)\n\n", ref.VarName, constructor(ref.Kind), resultType, ref.ModulePath+":"+ref.Name)
	}
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("convex-go-codegen: format generated Go: %w", err)
	}
	return formatted, nil
}

func isSourceFile(path string) bool {
	switch strings.ToLower(filepath.Ext(path)) {
	case ".ts", ".tsx", ".js", ".jsx":
		return true
	default:
		return false
	}
}

func stripCommentsAndStrings(source string) string {
	var out strings.Builder
	out.Grow(len(source))
	for i := 0; i < len(source); {
		if strings.HasPrefix(source[i:], "//") {
			out.WriteString("  ")
			i += 2
			for i < len(source) && source[i] != '\n' {
				out.WriteByte(' ')
				i++
			}
			continue
		}
		if strings.HasPrefix(source[i:], "/*") {
			out.WriteString("  ")
			i += 2
			for i < len(source) && !strings.HasPrefix(source[i:], "*/") {
				if source[i] == '\n' {
					out.WriteByte('\n')
				} else {
					out.WriteByte(' ')
				}
				i++
			}
			if i < len(source) {
				out.WriteString("  ")
				i += 2
			}
			continue
		}
		switch source[i] {
		case '\'', '"', '`':
			quote := source[i]
			out.WriteByte(' ')
			i++
			for i < len(source) {
				if source[i] == '\n' {
					out.WriteByte('\n')
					i++
					if quote != '`' {
						break
					}
					continue
				}
				if source[i] == '\\' && quote != '`' {
					out.WriteString("  ")
					i += 2
					continue
				}
				if source[i] == quote {
					out.WriteByte(' ')
					i++
					break
				}
				out.WriteByte(' ')
				i++
			}
		default:
			out.WriteByte(source[i])
			i++
		}
	}
	return out.String()
}

func modulePath(sourceDir, path string) (string, error) {
	relative, err := filepath.Rel(sourceDir, path)
	if err != nil {
		return "", err
	}
	relative = filepath.ToSlash(relative)
	ext := filepath.Ext(relative)
	return strings.TrimSuffix(relative, ext), nil
}

func refKind(callee string) string {
	switch callee {
	case "query", "internalQuery":
		return "query"
	case "mutation", "internalMutation":
		return "mutation"
	case "action", "internalAction":
		return "action"
	default:
		return ""
	}
}

func constructor(kind string) string {
	switch kind {
	case "query":
		return "NewQueryReference"
	case "mutation":
		return "NewMutationReference"
	case "action":
		return "NewActionReference"
	default:
		return ""
	}
}

func exportedVarName(modulePath string, functionName string) string {
	parts := splitIdentifierParts(modulePath + "/" + functionName)
	var builder strings.Builder
	for _, part := range parts {
		builder.WriteString(titleIdentifierPart(part))
	}
	out := builder.String()
	if out == "" {
		out = "Function"
	}
	if first, _ := utf8.DecodeRuneInString(out); first == utf8.RuneError || !unicode.IsLetter(first) {
		out = "Function" + out
	}
	return out
}

func splitIdentifierParts(value string) []string {
	fields := strings.FieldsFunc(value, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	parts := make([]string, 0, len(fields))
	for _, field := range fields {
		if field != "" {
			parts = append(parts, field)
		}
	}
	return parts
}

func titleIdentifierPart(part string) string {
	if part == "" {
		return ""
	}
	r, size := utf8.DecodeRuneInString(part)
	if r == utf8.RuneError {
		return ""
	}
	if unicode.IsDigit(r) {
		return "N" + part
	}
	return string(unicode.ToUpper(r)) + part[size:]
}

func isGoIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for i, r := range value {
		if i == 0 {
			if r != '_' && !unicode.IsLetter(r) {
				return false
			}
			continue
		}
		if r != '_' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}
